#version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

#jobs:
  #hello-world: # Delete this job when you get started
    #docker:
    #  - image: amazon/aws-cli
    #steps:
    #  - checkout
    #  - run:
    #      name: Say Hello
    #      command: |
    #        echo "Hello World"

version: 2.1
#Build-frontend
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "build-frontend"
          command: |
            cd frontend
            npm install
            npm run build
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: "test-frontend"
          command: |
            cd frontend
            npm install
            npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: "analyze-frontend"
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
#  build-frontend:

#  build-frontend:

#  test-frontend:

#  est-backend:

#  can-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

#workflows:
  #default:
    #jobs:
      #- hello-world
